spring:
  datasource:
    username: root
    password: 123456
    url:  jdbc:mysql://127.0.0.1:3306/school_life?serverTimezone=UTC
  main:
    banner-mode: off
    lazy-initialization: true
#  mvc:
#    static-path-pattern: /static/**
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  redis:
    port: 6379
    host: 127.0.0.1
logging:
  pattern:
    dateformat: HH:mm:ss

mybatis-plus:
  global-config:
    db-config:
      id-type: auto
#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl



